apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webwork-data-pvc
spec:
  volumeName: webwork-data-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webwork-db-pvc
spec:
  volumeName: webwork-db-pv
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
