apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: webwork-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mariadb-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webwork-db
  template:
    metadata:
      labels:
        app: webwork-db
    spec:
      containers:
        - name: webwork-db
          image: mariadb:10.4
          envFrom:
          - configMapRef:
              name: db-configmap
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: db
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: webwork-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: r
spec:
  selector:
    app: webwork-rserve
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 6311
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: rserve-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webwork-rserve
  template:
    metadata:
      labels:
        app: webwork-rserve
    spec:
      containers:
        - name: webwork-rserve
          image: muhanedyahya/ubcctlt-rserve:latest
---
apiVersion: v1
kind: Service
metadata:
  name: webwork
spec:
  selector:
    app: webwork
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      nodePort: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: webwork-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webwork
  template:
    metadata:
      labels:
        app: webwork
    spec:
      containers:
        - name: webwork
          image: muhanedyahya/webwork:configmap
          envFrom:
          - configMapRef:
              name: webwork-configmap
          volumeMounts:
            - mountPath: /opt/webwork/courses
              name: courses
      volumes:
        - name: courses
          persistentVolumeClaim:
            claimName: webwork-data-pvc