apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    # for production
    server: https://acme-v02.api.letsencrypt.org/directory
    # for testing
    # server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: yahya.muhaned@std.izu.edu.tr
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
      - http01:
          ingress:
            class: traefik